# See https://docs.github.com/en/actions/guides for documentation about GitHub
# Actions.

name: MinUnit Tests

# Run on all branches.
on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    #- name: Setup
    #  run: |
    #    git clone https://github.com/bxparks/AUnit

    #- name: Verify examples
    #  run: |
    #    make -C examples
    #    make -C examples/MemoryBenchmark epoxy

    - name: Verify tests
      run: |
        make -C src
        make -C tests
        make -C tests runtests
